version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando pre_build..."
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789.dkr.ecr.us-east-1.amazonaws.com)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Construyendo la imagen Docker..."
      - docker build -t hola-mundo-ecr:$IMAGE_TAG .
      - docker tag hola-mundo-ecr:$IMAGE_TAG 123456789.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-ecr:$IMAGE_TAG
  post_build:
    commands:
      - echo "Subiendo imagen a ECR..."
      - docker push 123456789.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-ecr:$IMAGE_TAG
      - echo "Exportando imagen..."
      - printf '[{"name":"hola-mundo","imageUri":"123456789.dkr.ecr.us-east-1.amazonaws.com/hola-mundo-ecr:%s"}]' $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
